// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotForza_web_app.Data;

#nullable disable

namespace Downloads.Migrations
{
    [DbContext(typeof(CarDataContext))]
    partial class CarDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("NotForza.Models.Car", b =>
                {
                    b.Property<int>("CarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarCost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CarDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CarGrade")
                        .HasColumnType("TEXT");

                    b.Property<string>("CarModel")
                        .HasColumnType("TEXT");

                    b.Property<string>("CarName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CarPicURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CarYear")
                        .HasColumnType("INTEGER");

                    b.HasKey("CarID");

                    b.ToTable("Car");
                });
#pragma warning restore 612, 618
        }
    }
}
